import axios from './axios';

export const bookingApi = {
  createLead: (data) => axios.post('/bookings/lead', data),
  getLeads: (params) => axios.get('/bookings/leads', { params }),
  updateLead: (id, data) => axios.patch(`/bookings/lead/${id}`, data),
  getLead: (id) => axios.get(`/bookings/lead/${id}`),
  deleteLead: (id) => axios.delete(`/bookings/lead/${id}`),
  createBooking: (data) => axios.post('/bookings', data),
  createQuotation: (data) => axios.post('/bookings/quotation', data),
  getQuotations: (params) => axios.get('/bookings/quotations', { params }),
  updateQuotationStatus: (id, status) => axios.patch(`/bookings/quotation/${id}/status`, { status }),
  createQuotationVersion: (quotationId, data) => axios.post(`/bookings/quotation/${quotationId}/version`, data),
  sendQuotationEmail: (id) => axios.post(`/bookings/quotation/${id}/send-email`),
  exportQuotationPDF: (id) => axios.get(`/bookings/quotation/${id}/pdf`, { responseType: 'blob' }),
  convertToBooking: (quotationId, data) => axios.post(`/bookings/quotation/${quotationId}/convert`, data),
  getBookings: (params) => axios.get('/bookings', { params }),
  getVouchers: (params) => axios.get('/bookings/vouchers', { params }),
  getBookingById: (id) => axios.get(`/bookings/${id}`),
  updateBooking: (id, data) => axios.patch(`/bookings/${id}`, data),
  deleteBooking: (id) => axios.delete(`/bookings/${id}`),
  createVoucher: (data) => axios.post('/bookings/voucher', data),
  exportVoucherPDF: (id) => axios.get(`/bookings/voucher/${id}/pdf`, { responseType: 'blob' }),
  sendVoucherEmail: (id) => axios.post(`/bookings/voucher/${id}/send`),
  // Invoice & Receipt APIs
  getInvoices: (params) => axios.get('/bookings/invoices', { params }),
  createInvoice: (data) => axios.post('/bookings/invoice', data),
  exportInvoicePDF: (id) => axios.get(`/bookings/invoice/${id}/pdf`, { responseType: 'blob' }),
  sendInvoiceEmail: (id) => axios.post(`/bookings/invoice/${id}/send-email`),
  deleteInvoice: (id) => axios.delete(`/bookings/invoice/${id}`),
  createReceipt: (data) => axios.post('/bookings/receipt', data),
  exportReceiptPDF: (id) => axios.get(`/bookings/receipt/${id}/pdf`, { responseType: 'blob' }),
  sendReceiptEmail: (id) => axios.post(`/bookings/receipt/${id}/send-email`),
  getReceipts: (params) => axios.get('/bookings/receipts', { params }),
  deleteReceipt: (id) => axios.delete(`/bookings/receipt/${id}`),
  recordPayment: (data) => axios.post('/billing/payments', data),
  deleteQuotation: (id) => axios.delete(`/bookings/quotation/${id}`),
  getReport: (type, period) => axios.get('/bookings/reports', { params: { type, period }, responseType: 'blob' }),
};
